// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM3arSXXjpgr7KAZ3UgKpiYsB3IbDvZjI',
    appId: '1:387126214676:web:c36afe7ee006b9672e2701',
    messagingSenderId: '387126214676',
    projectId: 'yukkemah-cc40f',
    authDomain: 'yukkemah-cc40f.firebaseapp.com',
    storageBucket: 'yukkemah-cc40f.firebasestorage.app',
    measurementId: 'G-8CWMBZ3GBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYV2vF6vg2NQH5rjv2-hsPoMLUKEkgjQ',
    appId: '1:387126214676:android:973796cd5f37c6a42e2701',
    messagingSenderId: '387126214676',
    projectId: 'yukkemah-cc40f',
    storageBucket: 'yukkemah-cc40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHU3Ce0Co1UnyUwhLrzpiIZXHGrnJvT8',
    appId: '1:387126214676:ios:b1395bd0db7a0ed22e2701',
    messagingSenderId: '387126214676',
    projectId: 'yukkemah-cc40f',
    storageBucket: 'yukkemah-cc40f.firebasestorage.app',
    iosBundleId: 'com.example.provisTugas3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHU3Ce0Co1UnyUwhLrzpiIZXHGrnJvT8',
    appId: '1:387126214676:ios:b1395bd0db7a0ed22e2701',
    messagingSenderId: '387126214676',
    projectId: 'yukkemah-cc40f',
    storageBucket: 'yukkemah-cc40f.firebasestorage.app',
    iosBundleId: 'com.example.provisTugas3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM3arSXXjpgr7KAZ3UgKpiYsB3IbDvZjI',
    appId: '1:387126214676:web:f3764bba6fd010552e2701',
    messagingSenderId: '387126214676',
    projectId: 'yukkemah-cc40f',
    authDomain: 'yukkemah-cc40f.firebaseapp.com',
    storageBucket: 'yukkemah-cc40f.firebasestorage.app',
    measurementId: 'G-283FRMM9TF',
  );

}